<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>test msg</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4f65def4-5dad-471c-b0fb-7c8149af0d70</testSuiteGuid>
   <testCaseLink>
      <guid>f9d68a17-936a-4bfd-938f-afc4fdfc4c5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Chuyển tiền 247</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ba2f9e67-2d78-4b0a-bafb-d288a18a3e64</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data3</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ba2f9e67-2d78-4b0a-bafb-d288a18a3e64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>stk</value>
         <variableId>a74a44d4-89b0-4f38-aee5-e6add6b5d280</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba2f9e67-2d78-4b0a-bafb-d288a18a3e64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>amount</value>
         <variableId>7e29ba53-e84c-4a3c-9c0b-2edd4f9c1f6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba2f9e67-2d78-4b0a-bafb-d288a18a3e64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>3ad4858e-a518-4d07-9b9c-7910bdf12f99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba2f9e67-2d78-4b0a-bafb-d288a18a3e64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>authcode</value>
         <variableId>84902f7f-da01-4021-ab5e-51b9d25734e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ba2f9e67-2d78-4b0a-bafb-d288a18a3e64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_msg</value>
         <variableId>aab64ef7-1e73-42cd-9e0f-6ae6e7085d9b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
