<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ngay hieu luc_card</name>
   <tag></tag>
   <elementGuidId>6b290523-ec0f-4df4-9e6d-d72e3692d284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#card-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07ccdc91-daf6-4f00-878d-cea440951d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f95b652c-cd06-4a27-95d9-1b30db366688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-number</value>
      <webElementGuid>2ef3b6bb-b6dc-45c0-a2cf-d12ce9bd1ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-number</value>
      <webElementGuid>6a1ff42b-a88b-494d-b276-fde2e89f46a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>761e5e72-f900-4979-ac62-90d465a7f62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>482597bc-9b99-4e34-9f21-b9743b6d2aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>555f7a31-150b-4695-a21f-a30e9e2ddb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>checkHasValueGa(this, 'Checkout - Nhập số thẻ', 'Nhập thông tin thẻ')</value>
      <webElementGuid>bd10520a-a676-4028-93b3-028b1b551e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-method</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fec249bb-b0f7-41d3-9502-4d323acceedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-number&quot;)</value>
      <webElementGuid>c1e28e56-30cd-46fa-b241-dfa4cf4b7e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card-number']</value>
      <webElementGuid>fbab2379-c668-4627-a113-6a2755cf68ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center-content']/div/div/div[3]/div[2]/form/div/label/input</value>
      <webElementGuid>cba9931f-5f7f-4a9a-b5d0-c05a64685eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>c6289a08-e636-4ccf-a4ad-cba65993d735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'card-number' and @name = 'card' and @placeholder = ' ']</value>
      <webElementGuid>e94ae5fe-c618-4a4f-a603-6332742b1ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
