<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Chuyen tien</name>
   <tag></tag>
   <elementGuidId>9629fdc2-cd7f-4b43-a899-9c194fa841a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main&quot;]/section/div[2]/div/div/div[3]/div[1]/form/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-show-transaction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5663b0be-9b7f-40c8-a88c-36e2f97c843e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-show-transaction</value>
      <webElementGuid>bd23f4ca-7d70-443e-9841-1b73cdbd5278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e656a876-ac8e-4b70-ac5b-8b5bf2d383e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn</value>
      <webElementGuid>a1cbe566-5092-40dc-9f79-3f16b65524d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xem giao dịch</value>
      <webElementGuid>11f7b1c9-abdc-4086-aada-bfc7cd60358f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-show-transaction&quot;)</value>
      <webElementGuid>934334c2-22b4-4bab-9802-c9e69d716b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-show-transaction']</value>
      <webElementGuid>a0e855f4-14fe-469d-be32-c179237aeef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyển tiếp'])[1]/following::button[1]</value>
      <webElementGuid>9ec18ef6-2081-4c08-a932-7552aeb4d685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WOORI BANK - NH Woori'])[1]/following::button[2]</value>
      <webElementGuid>0f0eaf28-57de-4ce0-a63a-d665f7467093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f066ed4d-7230-4396-bfe1-bb03f048ae4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-show-transaction' and @type = 'button' and (text() = 'Xem giao dịch' or . = 'Xem giao dịch')]</value>
      <webElementGuid>ff3c11b2-a56f-4bdd-9d4f-df7ab292a9a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
