<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Chuyen tien</name>
   <tag></tag>
   <elementGuidId>9629fdc2-cd7f-4b43-a899-9c194fa841a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main&quot;]/section/div[2]/div/div/div[3]/div[1]/div[2]/form/div/div/div[2]/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-show-transaction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>631ba05b-2b1a-489a-a745-8634a768c91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-show-transaction</value>
      <webElementGuid>6fe3aa53-d5db-4a0e-9f05-f2a3c9503dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ecb3f2e-f25a-48bb-9249-b09ffa3ee4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn</value>
      <webElementGuid>9fa1f213-ae35-43c3-9e7a-8929d47a8b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xem giao dịch</value>
      <webElementGuid>7c5cb3d3-5942-4d49-9147-1257dfc4dd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-show-transaction&quot;)</value>
      <webElementGuid>25a8adec-3388-4eac-a2e5-fc8b329a91d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-show-transaction']</value>
      <webElementGuid>8ae1fedb-1c9e-4c4a-97d0-b34c38473eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyển tiếp'])[1]/following::button[1]</value>
      <webElementGuid>f321510e-6aa4-44a7-bfce-99f3ee06ff5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WOORI BANK - NH Woori'])[1]/following::button[2]</value>
      <webElementGuid>2122a557-546d-43f7-9df4-3c6f8d08f299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>ecc5c347-9f02-437c-908a-de48e6d987b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-show-transaction' and @type = 'button' and (text() = 'Xem giao dịch' or . = 'Xem giao dịch')]</value>
      <webElementGuid>f4eb3f2f-deeb-48b7-a268-0ef3a49dec6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
