<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Xem giao dich</name>
   <tag></tag>
   <elementGuidId>291fe8bb-98d7-4bda-ae8c-eed68aca935a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-show-transaction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-show-transaction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8522ff40-b615-4759-874f-4ee608195818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-show-transaction</value>
      <webElementGuid>8c1c05ad-3a6e-4761-9617-a1b1f8f54a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68d551d8-580b-495a-9aad-fd3bcc308b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn</value>
      <webElementGuid>43096f73-50f4-46b8-a51a-c407aa8844ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xem giao dịch</value>
      <webElementGuid>984cfec8-adc5-473f-9cb0-aab32cfb6d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-show-transaction&quot;)</value>
      <webElementGuid>3604eef0-24c0-4ddb-8f1d-5a2b5e4bd965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-show-transaction']</value>
      <webElementGuid>6b1648b1-9575-432b-bf42-8422729d8a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyển tiếp'])[1]/following::button[1]</value>
      <webElementGuid>6b18ab24-6238-44b5-9b2c-0336e1ec081e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WOORI BANK - NH Woori'])[1]/following::button[2]</value>
      <webElementGuid>4693bec3-3c4a-4a2c-bae9-495555a86855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c83888cd-a7bf-477c-beb1-a51e39035e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-show-transaction' and @type = 'button' and (text() = 'Xem giao dịch' or . = 'Xem giao dịch')]</value>
      <webElementGuid>083cb124-3b1b-4790-9348-a4ce8911f25e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
