<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp1</name>
   <tag></tag>
   <elementGuidId>dfcebd7f-297e-4aaf-9d0a-c4338b33fb44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ap-otp-input-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ap-otp-input-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58aef52c-b879-4c14-abb8-3aa668a19476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>49f9d61c-f291-4a5f-8924-a1eb9271dd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ap-otp-input</value>
      <webElementGuid>d8dedc0f-5e30-4ffd-b3dd-da3713eaec03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap-otp-input-0</value>
      <webElementGuid>4518ea2b-b61f-4779-9f27-1837a3e9cd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4bd44548-7628-45e3-b347-05f9eb03118a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fa8a559f-d578-4b6f-9b17-0cff50f7944f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ed98dec-f54e-4d57-85ab-991c0eab5332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp[0]</value>
      <webElementGuid>7e38c070-5dc2-498b-954d-c3dc6d5aed8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap-otp-input-0&quot;)</value>
      <webElementGuid>d8fe2ae2-e416-433b-9670-3fb650afe9de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ap-otp-input-0']</value>
      <webElementGuid>c105c912-7ed0-494f-a145-b675856f6879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>fd99fe70-c3d7-4b10-a798-c8ddfa8bf6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = ' ' and @id = 'ap-otp-input-0' and @type = 'tel' and @name = 'otp[0]']</value>
      <webElementGuid>71f647c1-977b-44fa-9018-37509f1a6974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
