<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>otp5</name>
   <tag></tag>
   <elementGuidId>2da2d815-2dfb-4e34-a46d-980998176840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ap-otp-input-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ap-otp-input-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28df3b9a-2407-428b-93a3-28c9fbe9ca38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>38ae8c1e-d988-4bf3-b8a7-faf58ce61fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ap-otp-input</value>
      <webElementGuid>968c37db-bba6-42c0-9d37-bf799afa7e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap-otp-input-4</value>
      <webElementGuid>68a5ca77-6602-48b3-9c45-caab039bdc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>30daa229-3cb5-482f-addf-346a2c8713b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5dcc0cb0-cd40-4e70-a824-6ba52255bcc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70e0498a-1377-41af-99f0-1a067fb7d669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp[4]</value>
      <webElementGuid>07603c99-65aa-41e8-bce9-8cefc74f3466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap-otp-input-4&quot;)</value>
      <webElementGuid>6debe723-e06e-43ac-9ffe-2b20a717bfb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ap-otp-input-4']</value>
      <webElementGuid>ab3a938f-386f-4f3e-b7aa-7fa82de51c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[5]/input</value>
      <webElementGuid>3cec9ff8-c751-4292-929a-f8a763040a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = ' ' and @id = 'ap-otp-input-4' and @type = 'tel' and @name = 'otp[4]']</value>
      <webElementGuid>4bc181dd-bd27-436d-9a0c-0d5fb38ca9c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
