<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EN VI_rounded-circle</name>
   <tag></tag>
   <elementGuidId>1753dfb1-478c-4845-a58e-4e7208b6470e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/nav/ul/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>07fdc42c-851f-4454-b37c-c4619e825caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-gate.9pay.mobi/690cfeaf-5b70-4726-ab3b-0047bdcaba09-1700024020.jfif</value>
      <webElementGuid>415185e7-b419-4827-b0a3-6d388bca5dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>085950b2-0218-40c7-a48a-7d2737685b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
      <webElementGuid>741fb6da-9b01-42ec-afba-5a9c7fc155fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/nav[@class=&quot;header-nav&quot;]/ul[@class=&quot;d-flex align-items-center&quot;]/li[@class=&quot;nav-item dropdown dropdown-avatar&quot;]/a[@class=&quot;nav-link nav-profile d-flex align-items-center pe-0 dropdown-avatar-link&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
      <webElementGuid>f79d4f2a-a5d1-441e-9fdc-b95e51cc4e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/nav/ul/li/a/img</value>
      <webElementGuid>a928b1ab-92c3-4280-b001-c55835ec02e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Profile']</value>
      <webElementGuid>c3331b00-bce7-4856-8df9-88190a8e33d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>54eab657-077e-4b07-9a63-879fab23ebe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-gate.9pay.mobi/690cfeaf-5b70-4726-ab3b-0047bdcaba09-1700024020.jfif' and @alt = 'Profile']</value>
      <webElementGuid>f0a61a37-13e6-4aa5-be59-41ba983de8c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
