<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tiep tuc</name>
   <tag></tag>
   <elementGuidId>c7b54838-cc33-445b-bb8e-6cd396686a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='napasProcessBtn1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#napasProcessBtn1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1bc4f181-7338-4afb-9767-98a6d39a0da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e53af64f-6f45-4630-9a3e-3b866defd0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btnStyleSheet</value>
      <webElementGuid>eb426f89-7fd7-47f4-b183-6c691bc8aa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>napasProcessBtn1</value>
      <webElementGuid>c91982ec-94c3-4d4e-8027-26110978071a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>vi</value>
      <webElementGuid>7ba1934b-0165-4c12-929c-26f93dc80602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiếp tục</value>
      <webElementGuid>e059e664-09a6-4a28-8f63-6c574f4c5fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;napasProcessBtn1&quot;)</value>
      <webElementGuid>ab802751-e9c4-4f6a-9754-629da649d071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='napasProcessBtn1']</value>
      <webElementGuid>adda9de7-b6e5-4126-8661-454600dbf119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='napasModalBody']/div/div[3]/div[7]/div/div[2]/button[2]</value>
      <webElementGuid>46d9d447-4ac0-4922-8652-6cf5f4efd131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hủy'])[1]/following::button[1]</value>
      <webElementGuid>1a92b29f-3f83-42de-a4ae-e15cf33235ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hướng dẫn giao dịch thanh toán an toàn'])[1]/following::button[2]</value>
      <webElementGuid>9a9f5d6d-ef9e-45a5-b2e4-acaaf3418a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh sách Ngân hàng phát hành'])[2]/preceding::button[1]</value>
      <webElementGuid>458a69f1-62ce-4e58-96af-c10fd76a4248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hướng dẫn giao dịch thanh toán an toàn'])[2]/preceding::button[1]</value>
      <webElementGuid>6542c22b-5bd7-41d9-bacb-3459572ad481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tiếp tục']/parent::*</value>
      <webElementGuid>d3746f93-f6d5-4972-b61a-8515b2d76753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4d5813f0-e4fc-4303-ae48-e792f1fdae24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'napasProcessBtn1' and (text() = 'Tiếp tục' or . = 'Tiếp tục')]</value>
      <webElementGuid>623ca3ac-a96d-458a-b422-8ba1c8f9fb39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
