<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__napasOtpCode</name>
   <tag></tag>
   <elementGuidId>e8706ac5-a56b-46ff-a0e7-8fd31f88c061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='napasOtpCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#napasOtpCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b3b6dc7-ca4a-413d-94f0-728dd5575588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ecf4ba0-c29b-45ee-b175-bd10863351b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>85d979f2-e34c-4170-8575-cbd9424e8806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>napasOtpCode</value>
      <webElementGuid>4248d121-b804-488d-978e-b93da19c1081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mã xác thực (OTP)</value>
      <webElementGuid>de0e5de3-0bed-4cab-bb49-00565628cbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b42cdea8-697f-43e2-9379-44094336fef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>vi</value>
      <webElementGuid>2532eae9-0ddd-4eb9-b4ed-383d1a512616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>d8439f29-b906-4600-81aa-fab34bda8d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;napasOtpCode&quot;)</value>
      <webElementGuid>c7a012ed-d21a-4fc4-9fb3-8c0c42842bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='napasOtpCode']</value>
      <webElementGuid>34d52119-6c5d-4be3-b9c4-02a3ab7d3684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='napasDivOTP']/div/input</value>
      <webElementGuid>1a08e7f5-1101-43a0-acdc-004bdc6b7d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>3e1aa358-0b70-4172-a76f-7ba0499b5250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'napasOtpCode' and @placeholder = 'Mã xác thực (OTP)']</value>
      <webElementGuid>c769853e-4901-4659-8f39-92610137f40d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
